### ISSUE TITLE
sending to separate chats by mail address

### ISSUE THREAD

**Issue by sarangtc** [7orlum/SmtpTelegramGateway#3]
Is it possible to add the ability to separate chats by email address?

example:
to: [test1@google.com](mailto:test1@google.com) > chat ID: -111111111
to: [test333333@google.com](mailto:test333333@google.com) > chat ID: -222222222

OR (to prevent need of mapping files)

example2:
to: [-111111111@mytelegrambot.org](mailto:test1@google.com) > chat ID: -111111111
to: [-222222222@mytelegrambot.org](mailto:test333333@google.com) > chat ID: -222222222

**Comment by 7orlum** [comment]
https://github.com/7orlum/SmtpTelegramRelay/releases

**Comment by 7orlum** [comment]
Done, check out this release, please
https://github.com/7orlum/SmtpTelegramRelay/releases/tag/v2.0

**Comment by 7orlum** [comment]
Done
