### ISSUE TITLE
А есть готовый скомпилированный EXEшник ? 

### ISSUE THREAD

**Issue by PbIC9TuHa** [7orlum/SmtpTelegramGateway#4]
я нуб в C# ...но идея ваша мне в работе потребовалась 
попутался реализовать самостоятельно но не дорос .....
можно кинуть уже готовый EXE под винду ?

**Comment by 7orlum** [comment]
да, он тут в архиве https://github.com/7orlum/SmtpTelegramRelay/releases/download/v2.0/SmtpTelegramRelay.v2.0.win-x64.zip

**Comment by PbIC9TuHa** [comment]
спасибо .
